### ISSUE TITLE
enable follow in helm-ag will cause the screen flashes

### ISSUE THREAD

**Issue by freereaper** [quicknir/config#2]
Hi, quicknir
----
 After  using `(spacemacs/set-leader-keys "sb" (followize 'helm-do-ag-buffers helm-source-do-ag))`, the screen start to flash  when ag is searching.  
'

**Comment by quicknir** [comment]
I haven't noticed this I'm afraid. Can you observe it elsewhere?

**Comment by freereaper** [comment]
yes, I have tried in my office computer too, the same result. But I found this only happens when I use emacs in terminal. It works normally in gui.

**Comment by quicknir** [comment]
I'm seeing this issue also. I don't use the terminal emacs much except for quick edits, how I would use vim. The exact way to solve this would depend I think on how exactly you use it in the terminal. For me I launch a daemon with a specific name and have terminal clients connect to that, so I could conditionally check the name and bind SPC s b to either swoop or ag appropriately based on that. But I don't know if that would help you at all.

I will admit that the helm follow stuff is by far the part of my config that I'm least happy with. helm's approach to this doesn't make things as easy as they could be, and helm-ag's choices in using helm make it quite a bit harder. In ivy this stuff is handled nicely out of the box which is a big win but unfortunately there are other downsides preventing me from switching. Can't win them all I guess?

**Comment by freereaper** [comment]
Anyway, Thanks for your help.
