### ISSUE TITLE
Errors in cpp2 mode?

### ISSUE THREAD

**Issue by IanQS** [quicknir/config#4]
I get the following errors when copying cpp2 into my private/layers directory.

```
An error occurred while post-configuring company in layer cpp2 (error: (void-function spacemacs|add-company-backends))

An error occurred while post-configuring flycheck in layer cpp2 (error: (void-function spacemacs/enable-flycheck))
```

I've looked into my .spacemacs to try and solve the problem (by cross referencing against yours) + read the official spacemacs docs but I'm not sure what's up. Have you gotten these issues?

P.s: I noticed that in the spacemacs official documentation they add something similar to the following line in config.el

```
(spacemacs|defvar-company-backends c++-mode)
```

I'm not sure if it changes how your code works. 

Also sorry if this makes me seem ungrateful for you putting this up. I'm extremely grateful for this it makes my life much easier

**Comment by quicknir** [comment]
Are you on master or develop of spacemacs?

**Comment by IanQS** [comment]
I'm on master

**Comment by quicknir** [comment]
Yeah so this stuff is designed to work on develop. The idiomatic way of doing language layers has changed between master and develop. I recommend being on develop anyway; if you don't want to be too exposed just lock yourself to a commit and upgrade only occasionally.
